services:
  app:
    container_name: thesis-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      env_file: ".env" 
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run start:dev"